apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jenkins
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/smcervera/devops-tools.git'
    targetRevision: HEAD
    path: applications/jenkins
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: jenkins
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgresql
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/smcervera/devops-tools.git'
    targetRevision: HEAD
    path: applications/postgresql
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: postgresql
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true