apiVersion: v2
name: jenkins-local
description: A Helm chart for Kubernetes

type: application
version: 0.1.0
appVersion: "1.0"

dependencies:
- name: jenkins
  version: 4.11.1
  repository: https://charts.jenkins.io/
